### ISSUE TITLE
Notes repetitions 

### ISSUE THREAD

**Issue by mnns** [sweetcocoa/pop2piano#10]
Hi, thanks for this great project.
Most songs have this annoying unneeded repetition of notes sometimes instead of a longer 1 note for a duration of the same time.
1 + 1+ 1+ 1+ 1+ 1 should be just long 1.

Are there any configuration changes that I can apply to make improve that?

Thanks!

**Comment by sweetcocoa** [comment]
I'm sorry to say that there are no options like that currently. 
Repetition is a well-known problem that many NN models based on autoregressive generation suffer. 
Currently, the best way to fix that problem is to edit the MIDI directly using DAW Software like Logic.
