### ISSUE TITLE
Collab keyError on checkpoint

### ISSUE THREAD

**Issue by rodrix3855** [sweetcocoa/pop2piano#12]
I am trying to run your collab since I couldn't run it locally on Windows. Please help

**Comment by rodrix3855** [comment]
What is the pytorch-lightning version you used? This seems to be the issue.

**Comment by sweetcocoa** [comment]
If you just need to run Pop2Piano, You can try [HuggingFace](https://github.com/sweetcocoa/pop2piano/issues/11) Demo. It is simple to run.
