### ISSUE TITLE
How should I prepare the T5-small path

### ISSUE THREAD

**Issue by Liujingxiu23** [sweetcocoa/pop2piano#13]
self.t5config = T5Config.from_pretrained("t5-small")
https://huggingface.co/t5-small/tree/main is ok?

I use this, but when running inference,

wrapper = wrapper.load_from_checkpoint(ckpt, config=config).cuda()
ypeError: load_from_checkpoint() got an unexpected keyword argument 'config'

but when I remove config as input, error also occur as:
    wrapper = wrapper.load_from_checkpoint(ckpt).cuda()
  File "/data/liangmin/software/anaconda3/lib/python3.6/site-packages/pytorch_lightning/core/lightning.py", line 1360, in load_from_checkpoint
    model = cls._load_model_state(checkpoint)
  File "/data/liangmin/software/anaconda3/lib/python3.6/site-packages/pytorch_lightning/core/lightning.py", line 1390, in _load_model_state
    model = cls(*model_args)
TypeError: __init__() missing 1 required positional argument: 'config'

is it the version mismatch of pytorch_lightning?

**Comment by sweetcocoa** [comment]
Maybe it's version mismatch issue. 

can you try with libraries with these version?

```pretty-midi==0.2.9 omegaconf==2.1.1 youtube-dl==2021.12.17 transformers==4.16.1 pytorch-lightning essentia==2.1b6.dev609 note-seq==0.0.3 pyFluidSynth==1.3.0```

I will add requirements.txt to this repo. thanks.

**Comment by Liujingxiu23** [comment]
@sweetcocoa  Thank you for your reply, I will try again. 

how can I prepare the following dir?
self.t5config = T5Config.from_pretrained("t5-small")

**Comment by Liujingxiu23** [comment]
all problems sovled, and i can do inference successfully.
