### ISSUE TITLE
KeyError issue

### ISSUE THREAD

**Issue by kaarin1015** [sweetcocoa/pop2piano#15]
I have an error in the following part of the code and I would like to know how to solve it.
wrapper = wrapper.load_from_checkpoint("model-1999-val_0.67311615.ckpt", config=config).to(device)

Here is the error message:
KeyError                                  Traceback (most recent call last)
[<ipython-input-6-f76a479c8023>](https://localhost:8080/#) in <module>
      2 config = OmegaConf.load("pop2piano/config.yaml")
      3 wrapper = TransformerWrapper(config)
----> 4 wrapper = wrapper.load_from_checkpoint("model-1999-val_0.67311615.ckpt", config=config).to(device)
      5 model = "dpipqxiy"
      6 wrapper.eval()

[/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/migration/migration.py](https://localhost:8080/#) in _migrate_loop_global_step_to_progress_tracking(checkpoint)
     83     PR: #13645, #11805
     84     """
---> 85     global_step = checkpoint["global_step"]
     86     checkpoint.setdefault("loops", {"fit_loop": _get_fit_loop_initial_state_1_6_0()})
     87     checkpoint["loops"].setdefault("fit_loop", _get_fit_loop_initial_state_1_6_0())

KeyError: 'global_step'

Thank you in advance.

**Comment by susnato** [comment]
Hi @kaarin1015 please use `pytorch-lightning==1.8.4` to get rid of this issue.

**Comment by sweetcocoa** [comment]
Thanks @susnato ! Also, I have added requirements.txt in this repo.

**Comment by kaarin1015** [comment]
Thank you for your instruction.
